#!/usr/bin/env bash

commit_msg=$1

if [ $# -eq 0 ]; then
    echo "Error: You need to pass one parameter."
    echo "Usage: $0 \"<Commit message example>\""
    exit 1
fi

echo "Adding directory contents..."
git add .

echo "Commiting the contents..."
git commit -m "$commit_msg"

echo "Performing lazy push..."
current_branch=$(git branch --show-current)
git push origin $current_branch

echo "Lazy push performed successfully."

