name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create secrets files
        run: |
            mkdir -p secrets
            echo "${{ secrets.DB_PASSWORD }}" > secrets/db_password.txt
            echo "${{ secrets.DB_USER }}" > secrets/db_user.txt
            echo "${{ secrets.DB_NAME }}" > secrets/db_name.txt
            
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build & push web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/void-watcher-web:latest

      - name: Build & push app
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/void-watcher-app:latest

      - name: Deploy
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/void-watcher-web:latest
          docker pull ghcr.io/${{ github.repository_owner }}/void-watcher-app:latest
          docker stack deploy -c docker-stack.yml void-stack
