name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: zweihaka/void-watcher-web:latest

      - name: Build & push app
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: zweihaka/void-watcher-app:latest

      - name: Deploy
        run: |
          docker pull zweihaka/void-watcher-web:latest
          docker pull zweihaka/void-watcher-app:latest
          docker stack deploy -c docker-stack.yml void-stack
